# Beijing Multi-Site Air-Quality Analysis

In [2]:
import pandas as pd
import numpy as np
import random
from sklearn import preprocessing

In [3]:
data1 = pd.read_csv('Data//Original Data//PRSA_Data_Aotizhongxin_20130301-20170228.csv')
data2 = pd.read_csv('Data//Original Data//PRSA_Data_Changping_20130301-20170228.csv')
data3 = pd.read_csv('Data//Original Data//PRSA_Data_Dingling_20130301-20170228.csv')
data4 = pd.read_csv('Data//Original Data//PRSA_Data_Dongsi_20130301-20170228.csv')
data5 = pd.read_csv('Data//Original Data//PRSA_Data_Guanyuan_20130301-20170228.csv')
data6 = pd.read_csv('Data//Original Data//PRSA_Data_Gucheng_20130301-20170228.csv')
data7 = pd.read_csv('Data//Original Data//PRSA_Data_Huairou_20130301-20170228.csv')
data8 = pd.read_csv('Data//Original Data//PRSA_Data_Nongzhanguan_20130301-20170228.csv')
data9 = pd.read_csv('Data//Original Data//PRSA_Data_Shunyi_20130301-20170228.csv')
data10 = pd.read_csv('Data//Original Data//PRSA_Data_Tiantan_20130301-20170228.csv')
data11 = pd.read_csv('Data//Original Data//PRSA_Data_Wanliu_20130301-20170228.csv')
data12 = pd.read_csv('Data//Original Data//PRSA_Data_Wanshouxigong_20130301-20170228.csv')


#Loading all the files

In [4]:
data = data1.append(data2) #Appending the data into a single dataframe
data = data.append(data3) 
data = data.append(data4)
data = data.append(data5)
data = data.append(data6)
data = data.append(data7)
data = data.append(data8)
data = data.append(data9)
data = data.append(data10)
data = data.append(data11)
data = data.append(data12)

In [64]:
data.describe()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,...,DEWP,RAIN,wd,WSPM,PM25_AQI,PM10_AQI,SO2_AQI,NO2_AQI,CO_AQI,O3_AQI
count,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,...,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,79.629141,104.413639,6.042303,26.935418,1.074905,...,2.490822,0.064476,182.938625,1.729711,138.609854,72.135539,8.368896,25.085468,11.921375,23.000111
std,10122.116943,1.177198,3.448707,8.800102,6.922195,78.966825,89.815730,8.174526,18.414076,0.988020,...,13.787240,0.820624,108.884604,1.245914,82.742551,56.254464,11.192742,17.432015,10.855245,22.544899
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.109008,0.546011,0.087336,...,-43.400000,0.000000,22.709461,0.000000,8.333333,1.818182,0.151399,0.505565,0.970403,0.085680
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,21.000000,36.000000,1.145038,12.765957,0.436681,...,-8.900000,0.000000,68.445462,0.900000,69.148936,32.727273,1.590331,11.820331,4.852014,4.800000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,57.000000,84.000000,3.053435,23.936170,0.786026,...,3.000000,0.000000,179.548109,1.400000,150.789474,64.500000,4.240882,22.163121,8.733624,18.800000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,109.000000,144.000000,7.251908,37.234043,1.310044,...,15.100000,0.000000,291.529139,2.200000,178.157895,94.500000,10.072095,34.475965,14.556041,32.000000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,500.400000,605.000000,190.839695,154.255319,8.733624,...,29.100000,72.500000,350.471596,13.200000,499.933333,500.000000,152.050718,110.241408,92.336245,430.500000

## Replacing the Null Values with mean of Column

In [63]:

columns = ['PM2.5','PM10','SO2','NO2','CO','O3','TEMP','PRES','DEWP','RAIN','WSPM']

def replace_NaN(x):
    data[x].fillna((data[x].mean()), inplace=True) 

for x in columns:
    replace_NaN(x)

## Converting String Direction into Degrees

In [10]:
#Better way to convert String Variables to Degrees

Dictionary = {
    'N' : random.uniform(348.75, 360) or random.uniform(0,11.25), 
    'NNE' : random.uniform(11.25,33.75),
    'NE' : random.uniform(33.75,56.25),
    'ENE': random.uniform(56.25,78.75),
    'E' : random.uniform(78.75,101.25), 
    'ESE' : random.uniform(101.25,123.75), 
    'SE': random.uniform(123.75,146.25),
    'SSE' : random.uniform(146.25,168.75), 
    'S': random.uniform(168.75,191.25), 
    'SSW' : random.uniform(191.25,213.75), 
    'SW' : random.uniform(213.75,236.25),
    'WSW' : random.uniform(236.25,258.75),
    'W' : random.uniform(258.75,281.25), 
    'WNW' : random.uniform(281.25,303.75), 
    'NW' : random.uniform(303.75,326.25),
    'NNW' : random.uniform(326.25,348.75)
             }

In [15]:
for i in range(len(data)):
    if data['wd'].iloc[i] in Dictionary.keys():
        data['wd'].iloc[i] = Dictionary[data['wd'].iloc[i]]
    else:
        continue

C:\Users\dsola\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [20]:
# Replacing NaN values with average of Wind Direction
replace_NaN('wd')

In [65]:
data.describe()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,...,DEWP,RAIN,wd,WSPM,PM25_AQI,PM10_AQI,SO2_AQI,NO2_AQI,CO_AQI,O3_AQI
count,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,...,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000,420768.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,79.629141,104.413639,6.042303,26.935418,1.074905,...,2.490822,0.064476,182.938625,1.729711,138.609854,72.135539,8.368896,25.085468,11.921375,23.000111
std,10122.116943,1.177198,3.448707,8.800102,6.922195,78.966825,89.815730,8.174526,18.414076,0.988020,...,13.787240,0.820624,108.884604,1.245914,82.742551,56.254464,11.192742,17.432015,10.855245,22.544899
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.109008,0.546011,0.087336,...,-43.400000,0.000000,22.709461,0.000000,8.333333,1.818182,0.151399,0.505565,0.970403,0.085680
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,21.000000,36.000000,1.145038,12.765957,0.436681,...,-8.900000,0.000000,68.445462,0.900000,69.148936,32.727273,1.590331,11.820331,4.852014,4.800000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,57.000000,84.000000,3.053435,23.936170,0.786026,...,3.000000,0.000000,179.548109,1.400000,150.789474,64.500000,4.240882,22.163121,8.733624,18.800000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,109.000000,144.000000,7.251908,37.234043,1.310044,...,15.100000,0.000000,291.529139,2.200000,178.157895,94.500000,10.072095,34.475965,14.556041,32.000000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,500.400000,605.000000,190.839695,154.255319,8.733624,...,29.100000,72.500000,350.471596,13.200000,499.933333,500.000000,152.050718,110.241408,92.336245,430.500000

In [21]:
# Unit Conversion from ug/m^3 to ppb or ppm
# SO2 1 ppb = 2.62 µg/m3
# NO2 1 ppb = 1.88 µg/m3
# O3 1 ppb = 2.00 µg/m3
# CO 1 ppb = 1.145 µg/m
def convert_measurements():
    data['SO2'] = data['SO2']/2.62 # Measured in ppb
    data['NO2'] = data['NO2']/1.88  # Measured in ppb 
    data['O3'] = data['O3']/2.00   # Measured in ppb
    data['CO'] = data['CO']/(1.145*1000) #Measured in ppm
    
convert_measurements()

In [22]:
# Limiting the values of PM2.5 and PM10 since concentration higher than that will have same AQI. This will reduce  
for i in range(len(data)):
    if data['PM10'].iloc[i] > 605:
        data['PM10'].iloc[i] = 604
    if data['PM2.5'].iloc[i] > 500.4:
        data['PM2.5'].iloc[i] = 500.4
print('PM ranges limited')

PM ranges limited

# Calculating AQI for all Pollutants

## PM2.5

In [24]:
# Function to Calculate AQI of PM2.5 Particulate Matter
def aqi_pm25(a):
    conc_pm = a
#     print(conc_pm)
    aqi_range = [0.0,50.0,100.0,150.0,200.0,300,400,500]
    conc_range = [0,12,35.5,55.5,150.5,250.5,350.5,500.5]
    
    if conc_pm > conc_range[0] and conc_pm <= conc_range[1]:
        return conc_range[0],conc_range[1],aqi_range[0],aqi_range[1]
    
    elif conc_pm > conc_range[1] and conc_pm <= conc_range[2]:
        return conc_range[1],conc_range[2],aqi_range[1],aqi_range[2]

    elif conc_pm > conc_range[2] and conc_pm <= conc_range[3]:
        return conc_range[2],conc_range[3],aqi_range[2],aqi_range[3]

    elif conc_pm > conc_range[3] and conc_pm <= conc_range[4]:
        return conc_range[3],conc_range[4],aqi_range[3],aqi_range[4]

    elif conc_pm > conc_range[4] and conc_pm <= conc_range[5]:
        return conc_range[4],conc_range[5],aqi_range[4],aqi_range[5]

    elif conc_pm > conc_range[5] and conc_pm <= conc_range[6]:
        return conc_range[5],conc_range[6],aqi_range[5],aqi_range[6]
    
    elif conc_pm > conc_range[6] and conc_pm <= conc_range[7]:
        return conc_range[6],conc_range[7],aqi_range[6],aqi_range[7]


def calculate_aqi_pm25(a):
    aqi_current = 0
    conc_current = a
#     print(conc_current)
    conc_low,conc_high,aqi_low,aqi_high = aqi_pm25(conc_current)
#     print(conc_low,conc_high,aqi_low,aqi_high)
    aqi_current = (( aqi_high - aqi_low ) * ( conc_current - conc_low ) / (conc_high - conc_low)) + (aqi_low)
#     print(aqi_current)
    return aqi_current

In [26]:
data['PM25_AQI'] = 0
for i in range(len(data)):
    a = data['PM2.5'].iloc[i]
    data['PM25_AQI'].iloc[i] = calculate_aqi_pm25(a)

## PM10

In [27]:
# Function to Calculate AQI of PM10 Particulate Matter
def aqi_pm10(a):
    conc_pm = a
#     print(conc_pm)
    aqi_range = [0.0,50.0,100.0,150.0,200.0,300.0,400,500]
    conc_range = [0,55,155,255,355,425,505,605]
    
    if conc_pm > conc_range[0] and conc_pm <= conc_range[1]:
        return conc_range[0],conc_range[1],aqi_range[0],aqi_range[1]
    
    elif conc_pm > conc_range[1] and conc_pm <= conc_range[2]:
        return conc_range[1],conc_range[2],aqi_range[1],aqi_range[2]

    elif conc_pm > conc_range[2] and conc_pm <= conc_range[3]:
        return conc_range[2],conc_range[3],aqi_range[2],aqi_range[3]

    elif conc_pm > conc_range[3] and conc_pm <= conc_range[4]:
        return conc_range[3],conc_range[4],aqi_range[3],aqi_range[4]

    elif conc_pm > conc_range[4] and conc_pm <= conc_range[5]:
        return conc_range[4],conc_range[5],aqi_range[4],aqi_range[5]

    elif conc_pm > conc_range[5] and conc_pm <= conc_range[6]:
        return conc_range[5],conc_range[6],aqi_range[5],aqi_range[6]
    
    elif conc_pm > conc_range[6] and conc_pm <= conc_range[7]:
        return conc_range[6],conc_range[7],aqi_range[6],aqi_range[7]

def calculate_aqi_pm10(a):
    aqi_current = 0
    conc_current = a
#     print(conc_current)
    conc_low,conc_high,aqi_low,aqi_high = aqi_pm10(conc_current)
#     print(conc_low,conc_high,aqi_low,aqi_high)
    aqi_current = (( aqi_high - aqi_low ) * ( conc_current - conc_low ) / (conc_high - conc_low)) + (aqi_low)
#     print(aqi_current)
    return aqi_current

In [28]:
data['PM10_AQI'] = 0
for i in range(len(data)):
    a = data['PM10'].iloc[i]
    data['PM10_AQI'].iloc[i] = calculate_aqi_pm10(a)

## SO2

In [32]:
# Function to Calculate AQI of SO2 Particulate Matter
def aqi_so2(a):
    conc_pm = a
#     print(conc_pm)
    aqi_range = [0.0,50.0,100.0,150.0,200.0]
    conc_range = [0,36,76,186,304]
    
    if conc_pm > conc_range[0] and conc_pm <= conc_range[1]:
        return conc_range[0],conc_range[1],aqi_range[0],aqi_range[1]
    
    elif conc_pm > conc_range[1] and conc_pm <= conc_range[2]:
        return conc_range[1],conc_range[2],aqi_range[1],aqi_range[2]

    elif conc_pm > conc_range[2] and conc_pm <= conc_range[3]:
        return conc_range[2],conc_range[3],aqi_range[2],aqi_range[3]

    elif conc_pm > conc_range[3] and conc_pm <= conc_range[4]:
        return conc_range[3],conc_range[4],aqi_range[3],aqi_range[4]


def calculate_aqi_so2(a):
    aqi_current = 0
    conc_current = a
    #print(conc_current)
    conc_low,conc_high,aqi_low,aqi_high = aqi_so2(conc_current)
    #print(conc_low,conc_high,aqi_low,aqi_high)
    aqi_current = (( aqi_high - aqi_low ) * ( conc_current - conc_low ) / (conc_high - conc_low)) + (aqi_low)
    #print(aqi_current)
    return aqi_current

In [30]:
data['SO2_AQI'] = 0
for i in range(len(data)):
    a = data['SO2'].iloc[i]
    data['SO2_AQI'].iloc[i] = calculate_aqi_so2(a)

## NO2

In [33]:

def aqi_no2(a):
    conc_pm = a
#     print(conc_pm)
    aqi_range = [0.0,50.0,100.0,150.0,200.0,300.0,400.0,500.0]
    conc_range = [0,54,101,361,650,1250,1650,2049]

    if conc_pm > conc_range[0] and conc_pm <= conc_range[1]:
        return conc_range[0],conc_range[1],aqi_range[0],aqi_range[1]
    
    elif conc_pm > conc_range[1] and conc_pm <= conc_range[2]:
        return conc_range[1],conc_range[2],aqi_range[1],aqi_range[2]

    elif conc_pm > conc_range[2] and conc_pm <= conc_range[3]:
        return conc_range[2],conc_range[3],aqi_range[2],aqi_range[3]

    elif conc_pm > conc_range[3] and conc_pm <= conc_range[4]:
        return conc_range[3],conc_range[4],aqi_range[3],aqi_range[4]

    elif conc_pm > conc_range[4] and conc_pm <= conc_range[5]:
        return conc_range[4],conc_range[5],aqi_range[4],aqi_range[5]

    elif conc_pm > conc_range[5] and conc_pm <= conc_range[6]:
        return conc_range[5],conc_range[6],aqi_range[5],aqi_range[6]
    
    elif conc_pm > conc_range[6] and conc_pm <= conc_range[7]:
        return conc_range[6],conc_range[7],aqi_range[6],aqi_range[7]


def calculate_aqi_no2(a):
    aqi_current = 0
    conc_current = a
    #print(conc_current)
    conc_low,conc_high,aqi_low,aqi_high = aqi_no2(conc_current)
    #print(conc_low,conc_high,aqi_low,aqi_high)
    aqi_current = (( aqi_high - aqi_low ) * ( conc_current - conc_low ) / (conc_high - conc_low)) + (aqi_low)
    #print(aqi_current)
    return aqi_current

In [34]:
data['NO2_AQI'] = 0
for i in range(len(data)): 
    a = data['NO2'].iloc[i]
    data['NO2_AQI'].iloc[i] = calculate_aqi_no2(a)

## CO

In [35]:

def aqi_co(a):
    conc_pm = a
#     print(conc_pm)
    aqi_range = [0.0,50.0,100.0,150.0,200.0,300.0,400.0,500.0]
    conc_range = [0,4.5,9.5,12.5,15.5,30.5,40.5,50.5]

    if conc_pm > conc_range[0] and conc_pm <= conc_range[1]:
        return conc_range[0],conc_range[1],aqi_range[0],aqi_range[1]
    
    elif conc_pm > conc_range[1] and conc_pm <= conc_range[2]:
        return conc_range[1],conc_range[2],aqi_range[1],aqi_range[2]

    elif conc_pm > conc_range[2] and conc_pm <= conc_range[3]:
        return conc_range[2],conc_range[3],aqi_range[2],aqi_range[3]

    elif conc_pm > conc_range[3] and conc_pm <= conc_range[4]:
        return conc_range[3],conc_range[4],aqi_range[3],aqi_range[4]

    elif conc_pm > conc_range[4] and conc_pm <= conc_range[5]:
        return conc_range[4],conc_range[5],aqi_range[4],aqi_range[5]

    elif conc_pm > conc_range[5] and conc_pm <= conc_range[6]:
        return conc_range[5],conc_range[6],aqi_range[5],aqi_range[6]
    
    elif conc_pm > conc_range[6] and conc_pm <= conc_range[7]:
        return conc_range[6],conc_range[7],aqi_range[6],aqi_range[7]


def calculate_aqi_co(a):
    aqi_current = 0
    conc_current = a
    #print(conc_current)
    conc_low,conc_high,aqi_low,aqi_high = aqi_co(conc_current)
    #print(conc_low,conc_high,aqi_low,aqi_high)
    aqi_current = (( aqi_high - aqi_low ) * ( conc_current - conc_low ) / (conc_high - conc_low)) + (aqi_low)
    #print(aqi_current)
    return aqi_current

In [36]:
data['CO_AQI'] = 0
for i in range(len(data)):
    a = data['CO'].iloc[i]
    data['CO_AQI'].iloc[i] = calculate_aqi_co(a)

## O3

In [37]:
def aqi_o3(a):
    conc_pm = a
#     print(conc_pm)
    aqi_range = [0.0,100.0,150.0,200.0,300.0,400.0,500.0]
    conc_range = [0,125,165,205,405,505,605]

    if conc_pm > conc_range[0] and conc_pm <= conc_range[1]:
        return conc_range[0],conc_range[1],aqi_range[0],aqi_range[1]
    
    elif conc_pm > conc_range[1] and conc_pm <= conc_range[2]:
        return conc_range[1],conc_range[2],aqi_range[1],aqi_range[2]

    elif conc_pm > conc_range[2] and conc_pm <= conc_range[3]:
        return conc_range[2],conc_range[3],aqi_range[2],aqi_range[3]

    elif conc_pm > conc_range[3] and conc_pm <= conc_range[4]:
        return conc_range[3],conc_range[4],aqi_range[3],aqi_range[4]

    elif conc_pm > conc_range[4] and conc_pm <= conc_range[5]:
        return conc_range[4],conc_range[5],aqi_range[4],aqi_range[5]

    elif conc_pm > conc_range[5] and conc_pm <= conc_range[6]:
        return conc_range[5],conc_range[6],aqi_range[5],aqi_range[6]


def calculate_aqi_o3(a):
    aqi_current = 0
    conc_current = a
    #print(conc_current)
    conc_low,conc_high,aqi_low,aqi_high = aqi_o3(conc_current)
    #print(conc_low,conc_high,aqi_low,aqi_high)
    aqi_current = (( aqi_high - aqi_low ) * ( conc_current - conc_low ) / (conc_high - conc_low)) + (aqi_low)
    #print(aqi_current)
    return aqi_current

In [38]:
data['O3_AQI'] = 0
for i in range(len(data)):
    a = data['O3'].iloc[i]
    data['O3_AQI'].iloc[i] = calculate_aqi_o3(a)

In [41]:
data.to_csv("Data//Preprocessed Data//Preprocessed_data.csv")